checks:pylint:
  before_script:
  - sudo dnf install -y python3-pip
  - git clone https://github.com/QubesOS/qubes-core-qrexec ~/qubes-core-qrexec
  - pip3 install --quiet -r ci/requirements.txt
  script:
  - PYTHONPATH=test-packages:~/qubes-core-qrexec python3 -m pylint qubes
  stage: checks
checks:tests:
  after_script:
  - ci/codecov-wrapper -F unittests
  before_script:
  - sudo dnf install -y lvm2 vim-common python3-lxml python3-docutils
  - git clone https://github.com/QubesOS/qubes-core-qrexec ~/qubes-core-qrexec
  - pip3 install --user --quiet -r ci/requirements.txt
  - |
      set -e
      echo Installing ZFS after the CI requirements so after_script codecov-wrapper does not explode if ZFS install fails.
      sudo dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm
      echo $(uname -r) is the running kernel
      sudo dnf install -y zfs
      sudo modprobe zfs
  script:
  - PYTHONPATH=test-packages:~/qubes-core-qrexec ./run-tests
  stage: checks
  tags:
  - short-living-job
  - vm-runner
include:
- file: /r4.1/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-dom0.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
