#!/bin/bash -e
set -o pipefail

testvm=$1
if [ "$testvm" == "" ] ; then
    >&2 echo "First parameter must be the VM where you will run the tests."
    >&2 echo "Ideally qubes.VMShell service is 100% permitted from this VM to that VM."
    exit 2
fi
shift

bombshell-client "$testvm" which zfs >/dev/null || {
    >&2 echo "Install ZFS in "$testvm" using https://github.com/Rudd-O/zfs-fedora-installer script deploy-zfs as root."
    >&2 echo "That machine must have been booted using HVM virt_mode and GRUB kernel."
    exit 16
}

bombshell-client "$testvm" bash -c '
test -f .packages-installed || {
    packages="python3-libvirt python3-pytest lvm2"
    rpm -q $packages >/dev/null || sudo dnf install -y $packages
    touch .packages-installed
}
'

tar c . | bombshell-client "$testvm" bash -c 'mkdir -p qubes-core-admin && cd qubes-core-admin && tar x'
bombshell-client "$testvm" sudo bash -e -c '
cd qubes-core-admin

: "${PYTHON:=python3}"
: "${TESTPYTHONPATH:=test-packages}"

if [ -d ../core-qrexec/qrexec ] && ! $PYTHON -c "import qrexec" 2>/dev/null; then
    PYTHONPATH=${PYTHONPATH+"$PYTHONPATH:"}:../core-qrexec
fi

PYTHONPATH=${TESTPYTHONPATH}${PYTHONPATH+":${PYTHONPATH}"}
export PYTHONPATH

# "${PYTHON}" setup.py egg_info --egg-base "${TESTPYTHONPATH}"
"${PYTHON}" -m qubes.tests.run "$@"
' ignored "$@" qubes.tests.storage_zfs
